#!/bin/bash

PROGNAME=`basename $0`

usage_exit(){
    echo "$PROGNAME usage:  $PROGNAME SEQ1 [SEQ2] [-k K_MER] [-d OUTDIR] "
    exit 1
}

for OPT in "$@"
do
    case "$OPT" in
        '-h' | '--help')
            usage_exit
            ;;
        '-k')
            if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                echo "$PROGNAME error[-k]:  Designate match_size "
                exit 1
            fi
            KMER="$2"
            shift 2
            ;;
        '-d')
            if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                echo "$PROGNAME error[-d]:  Designate output directiory "
                exit 1
            elif [ ! -d "$2" ]; then
                echo "$PROGNAME error[-d]:  No such directory '$1' "
                exit 1
            fi
            OUTDIR="$2"
            shift 2
            ;;
        -*)
            echo "$PROGNAME error:  Unknown option '$1'"
            usage_exit
            ;;
        *)
            if [[ ! -z "$1" ]] && [[ ! "$1" =~ ^-+ ]]; then
                SEQ+=("$1")
                shift 1
            fi
            ;;
    esac
done

if [ "${#SEQ[*]}" -eq 2 ]; then
    SEQ1=${SEQ[0]}
    SEQ2=${SEQ[1]}
elif [ "${#SEQ[*]}" -eq 1 ]; then
    SEQ1=${SEQ[0]}
    SEQ2=${SEQ[0]}
else
    echo "$PROGNAME error:  Needs one or two seq_files"
    exit 1
fi


if [ -z "$KMER" ]; then
    KMER=20
fi

if [ -z "$OUTDIR" ]; then
    OUTDIR=$PWD
fi


comptool align $SEQ2 $SEQ1 -s -k $KMER

if [ $? -ne 0 ]; then exit 1; fi

SEQ1_NAME=`basename $SEQ1`
SEQ2_NAME=`basename $SEQ2`

FDATA=alignments-forward-startpos_${SEQ2_NAME}_${SEQ1_NAME}.tsv
BDATA=alignments-backward-startpos_${SEQ2_NAME}_${SEQ1_NAME}.tsv
tail -n +1 $BDATA >> $FDATA
FIG=${OUTDIR}/${SEQ1_NAME}_${SEQ2_NAME}_${KMER}.png

XC=`tail -n +2 $SEQ1 | wc -c | tr -d ' '`
XL=`tail -n +2 $SEQ1 | wc -l | tr -d ' '`
XLEN=`expr "$XC" - "$XL"`
YC=`tail -n +2 $SEQ2 | wc -c | tr -d ' '`
YL=`tail -n +2 $SEQ2 | wc -l | tr -d ' '`
YLEN=`expr "$YC" - "$YL"`
RATIO=`echo "scale=2; ${YLEN} / ${XLEN}" | bc`

gnuplot -e "
 set x2range [0 : ${XLEN}];
 set yrange [${YLEN} : 0];
 set x2tics ${XLEN}<10000 ? 1000 : (${XLEN}<100000 ? 5000 : 10000);
 set ytics  ${YLEN}<10000 ? 1000 : (${YLEN}<100000 ? 5000 : 10000);
 set mx2tics 5;
 set mytics 5;
 set tics out;
 set tics scale 1.5,0.5;
 set x2tics offset 0,-0.5;
 set ytics offset 0.8,0;
 set tics font 'DejaVuLGCSans,7';
 set x2label '${SEQ1_NAME}';
 set x2label font 'DejaVuLGCSans,10';
 set x2label offset 0,-0.8;
 set ylabel '${SEQ2_NAME}';
 set ylabel font 'DejaVuLGCSans,10';
 set ylabel offset 3.3,0;
 set nokey;
 unset xtics;
 set size ratio ${RATIO};
 set terminal png;
 set output '${FIG}';
 plot '${FDATA}' w p ps 0.15 lc rgb 'black'
 "

# set grid xtics ytics mxtics mytics;
# plot '${BDATA}' w p ps 0.45 lc rgb 'dark-green', '${FDATA}' w p pt 1 ps 0.45 lc rgb 'red'
# , '${FDATA}' w p pt 1 ps 0.15 lc rgb 'black'
rm $FDATA $BDATA
