#!/bin/bash

PROGNAME=`basename $0`

usage_exit(){
    echo "$PROGNAME usage:  $PROGNAME SEQ_FILE [-n NUM_SEQ_TO_PLOT] [-k K_MER] [-d OUT_DIR] "
    exit 1
}

for OPT in "$@"
do
    case "$OPT" in
        '-h' | '--help')
            usage_exit
            ;;
		'-n')
			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
				echo "PROGNAME error[-n]: Designate number of sequences to plot"
				exit 1
			fi
			NUM_SEQ="$2"
			shift 2
			;;
        '-k')
            if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                echo "$PROGNAME error[-k]:  Designate match_size "
                exit 1
            fi    
            K_MER="$2"
            shift 2
            ;;
        '-d')
            if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                echo "$PROGNAME error[-d]:  Designate output directiory "
                exit 1
            elif [ ! -d "$2" ]; then
                echo "$PROGNAME error[-d]:  No such directory '$1' "
                exit 1
            fi 
            OUT_DIR="$2"
            shift 2 
            ;;
        -*)
            echo "$PROGNAME error:  Unknown option '$1'"
            usage_exit
            ;;
        *)
            if [[ ! -z "$1" ]] && [[ ! "$1" =~ ^-+ ]]; then
                SEQ_FILE="$1"
                shift 1
            fi
            ;;
    esac
done


if [ -z "${SEQ_FILE}" ]; then
	echo "$PROGNAME error:  Designate fasta file"
	exit 1
fi

if [ -z "$K_MER" ]; then
    K_MER=20
fi

if [ -z "$OUT_DIR" ]; then
    OUT_DIR=dotplot
fi    

if [ ! -e "${OUT_DIR}" ]; then
	mkdir ${OUT_DIR}
fi   


TEMP_DIR=${SEQ_FILE}.temp`date +%Y%m%d_%H%M%S`
mkdir ${TEMP_DIR}
TEMP_FASTA=${TEMP_DIR}/temp.fasta
TEMP_LIST=${TEMP_DIR}/temp.list

fatt extract --start=0 --num=${NUM_SEQ} ${SEQ_FILE} > ${TEMP_FASTA}
sed -n '/^>/p' ${TEMP_FASTA} | sed 's/>//' > ${TEMP_LIST}

for name in `cat ${TEMP_LIST}`; do
	SINGLE_FASTA=${TEMP_DIR}/${name}.fa
	fatt extract --seq ${name} ${TEMP_FASTA} > ${SINGLE_FASTA}
	dop ${SINGLE_FASTA} -k ${K_MER} -d ${OUT_DIR}
done

rm -r ${TEMP_DIR}
